---

extends:
  - airbnb-base

parser: babel-eslint

env:
  node: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  no-console: 0
  no-useless-concat: 0
  prefer-const: 0
  prefer-template: 0
