---

extends:
  - airbnb-base
  - "plugin:jest/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  no-console: 0
